INSERT INTO course (school, department, course_number)
    VALUES ('San Jose State Univeristy', 'CSE', '101'),
    ('San Jose State Univeristy', 'CSE', '102'),
    ('San Jose State Univeristy', 'CSE', '103'),
    ('San Jose State Univeristy', 'CSE', '104'),
    ('Stanford Univeristy', 'CS', '101'),
    ('Stanford Univeristy', 'CS', '102'),
    ('Stanford Univeristy', 'CS', '103'),
    ('Stanford Univeristy', 'CS', '104'),
    ('Univeristy of California, Santa Cruz', 'CSE', '201'),
    ('Univeristy of California, Santa Cruz', 'CSE', '202'),
    ('Univeristy of California, Santa Cruz', 'CSE', '203'),
    ('Univeristy of California, Santa Cruz', 'CSE', '204'),
    ('Santa Clara Univeristy', 'COEN', '201'),
    ('Santa Clara Univeristy', 'COEN', '202'),
    ('Santa Clara Univeristy', 'COEN', '203'),
    ('Santa Clara Univeristy', 'COEN', '204');
